name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOCKER_COMPOSE_VERSION: 2

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:8.0.31
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Install NPM dependencies
        run: npm ci

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate

      - name: Set write permissions for build directory
        run: chmod -R 777 public/build

      - name: Run NPM Build
        run: npm run build

      - name: Run PHPUnit Tests
        run: vendor/bin/phpunit tests/

      - name: Lint code test with Laravel Pint
        run: ./vendor/bin/pint --test

      - name: Install Docker Compose
        run: |
          apt-get update
          apt-get install -y curl
          curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: docker compose build